# Generated by Django 3.0.7 on 2020-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortLink', models.CharField(max_length=200, verbose_name='shortened url given by user')),
                ('longLink', models.CharField(max_length=350, verbose_name='long url')),
            ],
        ),
    ]
