# Generated by Django 3.0.7 on 2020-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20200710_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortLink',
            field=models.CharField(max_length=200, unique=True, verbose_name='shortened url given by user'),
        ),
    ]
