# Generated by Django 3.0.7 on 2020-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20200710_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AlterField(
            model_name='link',
            name='shortLink',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='shortened url given by user'),
        ),
    ]
