# Generated by Django 3.1 on 2020-12-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_auto_20200828_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
